# Generated by Django 2.2.12 on 2021-03-14 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('cod_asig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_asig', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('cod_curso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dpto', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField()),
                ('dia', models.CharField(max_length=100, null=True)),
                ('horaInicio', models.CharField(blank=True, max_length=100, null=True)),
                ('horaFinal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=60)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(default='', max_length=60)),
                ('ciudad', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('1', 'Matricula'), ('2', 'Inscripcion'), ('3', 'Mensualidad'), ('4', 'Otros')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('codigo', models.IntegerField(default='999', primary_key=True, serialize=False)),
                ('Fecha_inicio', models.DateField(default='')),
                ('Fecha_final', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('cod_programa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_programa', models.CharField(max_length=30)),
                ('contenido_Aca', models.CharField(max_length=500)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('pagoRealizado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(default='', max_length=60)),
                ('nom_programa', models.CharField(default='', max_length=60)),
                ('referenciaPago', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Cursos',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('inscripcion_curso', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.InscripcionCurso')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_asignatura',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=100, null=True)),
                ('horaInicio', models.CharField(blank=True, max_length=100, null=True)),
                ('horaFinal', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Asignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='inscripcionPrograma',
            fields=[
                ('Id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('periodo', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Programas')),
            ],
        ),
        migrations.CreateModel(
            name='inscripcionEstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_curso', models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.detalle_curso')),
                ('estudiante', models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Realizacion', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Estudiantes')),
                ('cod_inscripcionPrograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma')),
                ('periodo', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='Id_inscripcionPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Cursos'),
        ),
        migrations.CreateModel(
            name='InscripcionAsignatura',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_inscripcionPrograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma')),
                ('nivel_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(default='', max_length=60)),
                ('ciudad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('cod_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Estudiantes')),
                ('id_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Pagos')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Docentes'),
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='InscripcionCurso',
            field=models.ForeignKey(blank=True, default='999', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.InscripcionCurso'),
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='Nivel_Curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_Cursos'),
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.departamento'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Docentes'),
        ),
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='actividades/')),
                ('Detalle_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.detalle_curso')),
                ('Nivel_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_Cursos')),
            ],
        ),
    ]
