# Generated by Django 3.1.4 on 2021-01-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('cod_asig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_asig', models.CharField(max_length=30)),
                ('contenido_academico', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=10)),
                ('nom_curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dpto', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('cod_docente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('user', models.OneToOneField(default=9999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=1)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(default='', max_length=60)),
                ('ciudad', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('1', 'Matricula'), ('2', 'Inscripcion'), ('3', 'Mensualidad'), ('4', 'Otros')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_inicio', models.DateField(default='')),
                ('Fecha_final', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=1)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(default='', max_length=60)),
                ('nom_programa', models.CharField(default='', max_length=60)),
                ('ciudad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('cod_programa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_programa', models.CharField(max_length=30)),
                ('contenido_Aca', models.CharField(max_length=500)),
                ('periodo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Cursos',
            fields=[
                ('nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.cursos')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_asignatura',
            fields=[
                ('nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('horario_inicial', models.DateTimeField(blank=True, null=True)),
                ('horario_final', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.asignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_curso',
            fields=[
                ('grupo', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_inicial', models.DateTimeField(blank=True, null=True)),
                ('horario_final', models.DateTimeField(blank=True, null=True)),
                ('Nivel_Curso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.nivel_cursos')),
                ('estudiante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='Programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.departamento'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas'),
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Realizacion', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes')),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas')),
                ('periodo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo')),
            ],
            options={
                'unique_together': {('Programa', 'Estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Detalle_Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes')),
                ('Pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.pagos')),
            ],
            options={
                'unique_together': {('Estudiante', 'Pagos')},
            },
        ),
    ]
