# Generated by Django 3.1 on 2020-08-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=10)),
                ('nom_curso', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('cod_docente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('user', models.OneToOneField(default=9999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=1)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('user', models.OneToOneField(default=9999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_inicio', models.DateTimeField()),
                ('h_final', models.DateTimeField()),
                ('dia', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('cod_programa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_programa', models.CharField(max_length=30)),
                ('contenido_Aca', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('1', 'Matricula'), ('2', 'Inscripcion'), ('3', 'Mensualidad'), ('4', 'Otros')], default='', max_length=1)),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Cursos',
            fields=[
                ('nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.cursos')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='Horario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.horarios'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='Programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas'),
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('cod_asig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_asig', models.CharField(max_length=30)),
                ('contenido_academico', models.CharField(max_length=500)),
                ('nivel', models.IntegerField()),
                ('horario', models.DateTimeField()),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes')),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Realizacion', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes')),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas')),
            ],
            options={
                'unique_together': {('Programa', 'Estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Detalle_Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes')),
                ('Pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.pagos')),
            ],
            options={
                'unique_together': {('Estudiante', 'Pagos')},
            },
        ),
    ]
