# Generated by Django 2.2.12 on 2021-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='detalle_curso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='nivel_curso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
