# Generated by Django 2.2.12 on 2021-03-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='detalle_curso',
            new_name='Detalle_curso',
        ),
        migrations.RenameField(
            model_name='actividades',
            old_name='nivel_curso',
            new_name='Nivel_curso',
        ),
    ]
