# Generated by Django 2.2.12 on 2021-02-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionprograma',
            name='cod_periodo',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='codigo',
            field=models.AutoField(default='999', primary_key=True, serialize=False),
        ),
    ]
