# Generated by Django 3.1 on 2020-08-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturas',
            name='Docente',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='Programa',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Programa',
        ),
        migrations.AddField(
            model_name='programas',
            name='Asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.asignaturas'),
        ),
        migrations.AddField(
            model_name='programas',
            name='Curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.cursos'),
        ),
    ]
