# Generated by Django 2.2.12 on 2021-03-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_curso',
            name='inscripcion_programa',
            field=models.ForeignKey(blank=True, default='999', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
    ]
