# Generated by Django 2.2.12 on 2021-03-14 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0002_detalle_curso_inscripcion_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionestudiantecurso',
            name='inscripcion_programa',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
    ]
