# Generated by Django 3.0.7 on 2021-01-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0002_auto_20210124_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ciudad',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad'),
        ),
    ]
