# Generated by Django 3.1 on 2020-08-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0002_auto_20200826_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='Curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='Horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.horarios'),
            preserve_default=False,
        ),
    ]
