# Generated by Django 3.1 on 2020-08-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0003_auto_20200826_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='Asignatura',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='Curso',
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='Programa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.programas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel_cursos',
            name='Docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Horario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.horarios'),
        ),
    ]
