# Generated by Django 2.2.12 on 2021-03-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0003_inscripcionestudiantecurso_inscripcion_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionestudiantecurso',
            name='inscripcion_programa',
        ),
        migrations.AddField(
            model_name='inscripcionestudiantecurso',
            name='inscripcion_programa_estudiante',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.InscripcionEstudiante'),
        ),
    ]
