# Generated by Django 3.0.7 on 2021-01-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0003_auto_20210124_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='periodo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
    ]
