# Generated by Django 2.2.12 on 2021-02-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0003_auto_20210203_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='cod_curso',
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='nivel_curso',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_Cursos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InscripcionAsignatura',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_inscripcionPrograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma')),
                ('nivel_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_asignatura')),
            ],
        ),
    ]
