# Generated by Django 3.0.7 on 2020-09-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0003_auto_20200904_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturas',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='h_final',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='h_inicio',
        ),
    ]
