# Generated by Django 2.2.12 on 2021-03-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0004_auto_20210314_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='curso_musica',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso_musica',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
