# Generated by Django 2.2.12 on 2021-02-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0004_auto_20210203_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturas',
            name='cod_inscripcionPrograma',
        ),
    ]
