# Generated by Django 3.0.7 on 2020-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0005_auto_20200907_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='Horario',
        ),
        migrations.AddField(
            model_name='cursos',
            name='dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='cursos',
            name='h_final',
            field=models.CharField(choices=[('1', '10:00'), ('2', '11:00'), ('3', '12:00'), ('4', '13:00'), ('5', '14:00'), ('6', '15:00'), ('7', '16:00'), ('8', '17:00'), ('9', '18:00')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='cursos',
            name='h_inicio',
            field=models.CharField(choices=[('1', '8:00'), ('2', '9:00'), ('3', '10:00'), ('4', '11:00'), ('5', '12:00'), ('6', '13:00'), ('7', '14:00'), ('8', '15:00'), ('9', '16:00'), ('10', '17:00'), ('11', '18:00')], default='1', max_length=5),
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
