# Generated by Django 2.2.12 on 2021-03-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0005_auto_20210320_0232'),
    ]

    operations = [
    ]
