# Generated by Django 2.2.12 on 2021-02-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0006_usuario_referenciapago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionprograma',
            old_name='cod_periodo',
            new_name='periodo',
        ),
        migrations.RenameField(
            model_name='inscripcionprograma',
            old_name='cod_programa',
            new_name='programa',
        ),
    ]
