# Generated by Django 2.2.12 on 2021-03-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0007_auto_20210320_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionasignatura',
            name='periodo',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcionasignatura',
            name='Id_inscripcionPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
    ]
