# Generated by Django 3.1 on 2020-09-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionacademica', '0007_auto_20200908_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=1)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
