# Generated by Django 2.2.12 on 2021-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0007_auto_20210207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='tipo',
            field=models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=20),
        ),
    ]
