# Generated by Django 2.2.12 on 2021-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0008_auto_20210215_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=60),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='tipo',
            field=models.CharField(choices=[('1', 'Cedula Ciudadania'), ('2', 'Tarjeta de identidad'), ('3', 'Cedula de Extranjeria'), ('4', 'Certificado Cabildo '), ('5', 'Pasaporte')], default='2', max_length=60),
        ),
    ]
