# Generated by Django 3.1.6 on 2021-02-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0009_auto_20210216_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='pagoRealizado',
        ),
    ]
