# Generated by Django 2.2.12 on 2021-03-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0009_inscripcionasignatura_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel_asignatura',
            name='inscripcion_asignatura',
        ),
        migrations.AddField(
            model_name='inscripcionasignatura',
            name='nivel',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_asignatura'),
            preserve_default=False,
        ),
    ]
