# Generated by Django 3.1.4 on 2020-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0010_auto_20201230_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='Fecha_inscripcion',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='Fecha_final',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='Fecha_inicio',
            field=models.DateField(default=''),
        ),
    ]
