# Generated by Django 2.2.12 on 2021-03-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0010_remove_docentes_pagorealizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_curso',
            name='cod_estudiante',
        ),
        migrations.AddField(
            model_name='programas',
            name='duracion',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='inscripcionEstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_curso', models.ForeignKey(default='nulo', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.detalle_curso')),
                ('estudiante', models.ForeignKey(default='nulo', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Estudiantes')),
            ],
        ),
    ]
