# Generated by Django 2.2.12 on 2021-03-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0011_auto_20210323_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='Nivel_curso',
        ),
        migrations.AddField(
            model_name='actividades',
            name='Nivel_asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Nivel_asignatura'),
        ),
    ]
