# Generated by Django 3.1.4 on 2020-12-31 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0011_auto_20201230_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dpto', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nom_programa',
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='estudiante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.estudiantes'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='direccion',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='programas',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.CreateModel(
            name='Nivel_asignatura',
            fields=[
                ('nivel', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.docentes')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.asignaturas')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.ciudad'),
        ),
    ]
