# Generated by Django 2.2.12 on 2021-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0012_auto_20210303_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel_asignatura',
            name='horario_final',
        ),
        migrations.RemoveField(
            model_name='nivel_asignatura',
            name='horario_inicial',
        ),
        migrations.AddField(
            model_name='nivel_asignatura',
            name='dia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nivel_asignatura',
            name='horaFinal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nivel_asignatura',
            name='horaInicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
