# Generated by Django 2.2.12 on 2021-03-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0012_auto_20210323_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel_cursos',
            name='periodo',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
    ]
