# Generated by Django 2.2.12 on 2021-03-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0013_nivel_cursos_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncurso',
            name='periodo',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
            preserve_default=False,
        ),
    ]
