# Generated by Django 2.2.12 on 2021-03-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0013_auto_20210304_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel_cursos',
            old_name='cod_Curso',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='nivel_cursos',
            old_name='cod_Docente',
            new_name='Docente',
        ),
    ]
