# Generated by Django 2.2.12 on 2021-03-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0014_auto_20210304_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_curso',
            name='Inscripcion_programa',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
            preserve_default=False,
        ),
    ]
