# Generated by Django 2.2.12 on 2021-03-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0015_detalle_curso_inscripcion_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_curso',
            name='Inscripcion_programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
    ]
