# Generated by Django 2.2.12 on 2021-03-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0016_auto_20210307_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_curso',
            name='Inscripcion_programa',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='nivel_curso',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='nivel_cursos',
            name='Curso',
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.Cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel_cursos',
            name='inscripcion_curso',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.InscripcionCurso'),
        ),
    ]
