# Generated by Django 2.2.12 on 2021-03-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0018_auto_20210308_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='Id_inscripcionPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.inscripcionPrograma'),
        ),
    ]
