# Generated by Django 2.2.12 on 2021-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0018_auto_20210411_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='isActual',
            field=models.BooleanField(default=False),
        ),
    ]
