# Generated by Django 2.2.12 on 2021-03-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0019_auto_20210308_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_curso',
            name='periodo',
        ),
    ]
