# Generated by Django 2.2.12 on 2021-03-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionacademica', '0020_remove_detalle_curso_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_curso',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionacademica.periodo'),
        ),
    ]
